versions:
  - version: 2024-04-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.Workloads/EpicVirtualInstance/preview/2024-04-01-preview/EpicVirtualInstance.json
