versions:
  - version: 2025-05-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.ErrorAtlas/preview/2025-05-01-preview/microsoft-erroratlas.json
  - version: 2026-06-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.ErrorAtlas/preview/2026-06-01-preview/microsoft-erroratlas.json
