versions:
  - version: 2025-05-12-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.OneDriveSharePoint/preview/2025-05-12-preview/microsoft-onedrivesharepoint.json
