versions:
  - version: 2024-10-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.Monitor/Operations/preview/2024-10-01-preview/operations.json
  - version: 2025-03-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.Monitor/Operations/preview/2025-03-01-preview/operations.json
  - version: 2025-05-03-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.Monitor/Operations/preview/2025-05-03-preview/operations.json
  - version: 2025-06-03-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.Monitor/Operations/preview/2025-06-03-preview/operations.json
  - version: 2026-04-01
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.Monitor/Operations/stable/2026-04-01/operations.json
