versions:
  - version: 2025-02-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.EntraidGovernance/preview/2025-02-01-preview/openapi.json
  - version: 2025-06-13-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.EntraidGovernance/preview/2025-06-13-preview/openapi.json
