versions:
  - version: 2024-11-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.DeviceOnboarding/preview/2024-11-01-preview/DeviceOnboarding.json
  - version: 2024-12-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.DeviceOnboarding/preview/2024-12-01-preview/DeviceOnboarding.json
  - version: 2025-05-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.DeviceOnboarding/preview/2025-05-01-preview/DeviceOnboarding.json
