versions:
  - version: 2024-09-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.Premonition/preview/2024-09-01-preview/insights.json
  - version: 2025-04-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.Premonition/preview/2025-04-01-preview/insights.json
  - version: 2025-05-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.Premonition/preview/2025-05-01-preview/insights.json
  - version: 2025-06-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.Premonition/preview/2025-06-01-preview/insights.json
