versions:
  - version: 2023-10-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.Monitor/preview/2023-10-01-preview/azuremonitor.json
  - version: 2024-01-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.Monitor/preview/2024-01-01-preview/azuremonitor.json
  - version: 2024-10-01
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.Monitor/stable/2024-10-01/azuremonitor.json
