versions:
  - version: 2025-10-30-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.ComputeBulkActions/preview/2025-10-30-preview/computebulkactions.json
  - version: 2026-02-10-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.ComputeBulkActions/preview/2026-02-10-preview/computebulkactions.json
