versions:
  - version: 2023-01-01-preview
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.SaaSHub/preview/2023-01-01-preview/saasHub.json
      - ../resource-manager/Microsoft.SaaSHub/preview/2023-01-01-preview/saasHubOperations.json
  - version: 2024-09-30-preview
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.SaaSHub/preview/2024-09-30-preview/openapi.json
  - version: 2025-07-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.SaaSHub/preview/2025-07-01-preview/openapi.json
  - version: 2026-03-31-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.SaaSHub/preview/2026-03-31-preview/openapi.json
