versions:
  - version: 2023-04-01-preview
    source: typespec
    swagger-files:
      - preview/2023-04-01-preview/anyscale.json
  - version: 2026-02-01-preview
    source: typespec
    swagger-files:
      - preview/2026-02-01-preview/anyscale.json
  - version: 2026-07-01-preview
    source: typespec
    swagger-files:
      - preview/2026-07-01-preview/anyscale.json
