versions:
  - version: 2024-12-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.Workloads/VirtualInstance/preview/2024-12-01-preview/VirtualInstance.json
  - version: 2025-06-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.Workloads/VirtualInstance/preview/2025-06-01-preview/VirtualInstance.json
  - version: 2026-02-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.Workloads/VirtualInstance/preview/2026-02-01-preview/VirtualInstance.json
  - version: 2026-07-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.Workloads/VirtualInstance/preview/2026-07-01-preview/VirtualInstance.json
