versions:
  - version: 2025-04-30-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.Dsts/preview/2025-04-30-preview/dsts.json
  - version: 2025-05-23-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.Dsts/preview/2025-05-23-preview/dsts.json
  - version: 2025-06-10-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.Dsts/preview/2025-06-10-preview/dsts.json
