versions:
  - version: 2024-10-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.ChangeSafety/ChangeControl/preview/2024-10-01-preview/ChangeControl.json
  - version: 2025-03-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.ChangeSafety/ChangeControl/preview/2025-03-01-preview/ChangeControl.json
  - version: 2025-07-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.ChangeSafety/ChangeControl/preview/2025-07-01-preview/ChangeControl.json
  - version: 2025-09-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.ChangeSafety/ChangeControl/preview/2025-09-01-preview/ChangeControl.json
  - version: 2026-01-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.ChangeSafety/ChangeControl/preview/2026-01-01-preview/ChangeControl.json
