versions:
  - version: 2026-02-01-preview
    source: typespec
    swagger-files:
      - ../../resource-manager/Microsoft.ApplicationMigration/Oracle/preview/2026-02-01-preview/OracleWorkloadsDiscovery.json
