versions:
  - version: 2024-12-01
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.AwsConnector/stable/2024-12-01/configServiceConfigurationRecorder.json
  - version: 2026-05-31-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.AwsConnector/preview/2026-05-31-preview/configServiceConfigurationRecorder.json
