versions:
  - version: 2019-10-10-preview
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.Communication/preview/2019-10-10-preview/CommunicationService-private.json
      - ../resource-manager/Microsoft.Communication/preview/2019-10-10-preview/CommunicationService.json
  - version: 2020-08-20
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.Communication/stable/2020-08-20/CommunicationService-private.json
      - ../resource-manager/Microsoft.Communication/stable/2020-08-20/CommunicationService.json
  - version: 2020-08-20-preview
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.Communication/preview/2020-08-20-preview/CommunicationService-private.json
      - ../resource-manager/Microsoft.Communication/preview/2020-08-20-preview/CommunicationService.json
  - version: 2021-09-09-privatepreview
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.Communication/preview/2021-09-09-privatepreview/EventGridFilters.json
  - version: 2021-10-01-preview
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.Communication/preview/2021-10-01-preview/CommunicationServices.json
      - ../resource-manager/Microsoft.Communication/preview/2021-10-01-preview/Domains.json
      - ../resource-manager/Microsoft.Communication/preview/2021-10-01-preview/EmailServices.json
  - version: 2022-03-29-preview
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.Communication/preview/2022-03-29-preview/CommunicationServices.json
      - ../resource-manager/Microsoft.Communication/preview/2022-03-29-preview/Domains.json
      - ../resource-manager/Microsoft.Communication/preview/2022-03-29-preview/EmailServices.json
  - version: 2022-07-01-preview
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.Communication/preview/2022-07-01-preview/CommunicationServices.json
      - ../resource-manager/Microsoft.Communication/preview/2022-07-01-preview/Domains.json
      - ../resource-manager/Microsoft.Communication/preview/2022-07-01-preview/EmailServices.json
  - version: 2022-10-01-preview
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.Communication/preview/2022-10-01-preview/CommunicationServices.json
      - ../resource-manager/Microsoft.Communication/preview/2022-10-01-preview/Domains.json
      - ../resource-manager/Microsoft.Communication/preview/2022-10-01-preview/EmailServices.json
  - version: 2023-03-01-preview
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.Communication/preview/2023-03-01-preview/CommunicationServices.json
      - ../resource-manager/Microsoft.Communication/preview/2023-03-01-preview/Domains.json
      - ../resource-manager/Microsoft.Communication/preview/2023-03-01-preview/EmailServices.json
      - ../resource-manager/Microsoft.Communication/preview/2023-03-01-preview/SenderUsernames.json
  - version: 2023-03-31
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.Communication/stable/2023-03-31/CommunicationServices.json
      - ../resource-manager/Microsoft.Communication/stable/2023-03-31/Domains.json
      - ../resource-manager/Microsoft.Communication/stable/2023-03-31/EmailServices.json
      - ../resource-manager/Microsoft.Communication/stable/2023-03-31/SenderUsernames.json
  - version: 2023-04-01
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.Communication/stable/2023-04-01/CommunicationServices.json
      - ../resource-manager/Microsoft.Communication/stable/2023-04-01/Domains.json
      - ../resource-manager/Microsoft.Communication/stable/2023-04-01/EmailServices.json
      - ../resource-manager/Microsoft.Communication/stable/2023-04-01/SenderUsernames.json
  - version: 2023-04-01-preview
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.Communication/preview/2023-04-01-preview/CommunicationServices.json
      - ../resource-manager/Microsoft.Communication/preview/2023-04-01-preview/Domains.json
      - ../resource-manager/Microsoft.Communication/preview/2023-04-01-preview/EmailServices.json
      - ../resource-manager/Microsoft.Communication/preview/2023-04-01-preview/SenderUsernames.json
  - version: 2023-06-01-preview
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.Communication/preview/2023-06-01-preview/CommunicationServices.json
      - ../resource-manager/Microsoft.Communication/preview/2023-06-01-preview/Domains.json
      - ../resource-manager/Microsoft.Communication/preview/2023-06-01-preview/EmailServices.json
      - ../resource-manager/Microsoft.Communication/preview/2023-06-01-preview/SenderUsernames.json
      - ../resource-manager/Microsoft.Communication/preview/2023-06-01-preview/SuppressionLists.json
  - version: 2023-11-06-preview
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.Communication/preview/2023-11-06-preview/CommunicationServices.json
      - ../resource-manager/Microsoft.Communication/preview/2023-11-06-preview/Domains.json
      - ../resource-manager/Microsoft.Communication/preview/2023-11-06-preview/EmailServices.json
      - ../resource-manager/Microsoft.Communication/preview/2023-11-06-preview/SenderUsernames.json
  - version: 2023-11-21-preview
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.Communication/preview/2023-11-21-preview/CommunicationServices.json
      - ../resource-manager/Microsoft.Communication/preview/2023-11-21-preview/Domains.json
      - ../resource-manager/Microsoft.Communication/preview/2023-11-21-preview/EmailServices.json
      - ../resource-manager/Microsoft.Communication/preview/2023-11-21-preview/SenderUsernames.json
  - version: 2023-12-25-preview
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.Communication/preview/2023-12-25-preview/CommunicationServices.json
      - ../resource-manager/Microsoft.Communication/preview/2023-12-25-preview/Domains.json
      - ../resource-manager/Microsoft.Communication/preview/2023-12-25-preview/EmailServices.json
      - ../resource-manager/Microsoft.Communication/preview/2023-12-25-preview/SenderUsernames.json
  - version: 2024-01-01-preview
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.Communication/preview/2024-01-01-preview/CommunicationServicesGccm-private.json
      - ../resource-manager/Microsoft.Communication/preview/2024-01-01-preview/CommunicationServicesGccm.json
  - version: 2024-09-01-preview
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.Communication/preview/2024-09-01-preview/CommunicationServices.json
      - ../resource-manager/Microsoft.Communication/preview/2024-09-01-preview/Domains.json
      - ../resource-manager/Microsoft.Communication/preview/2024-09-01-preview/EmailServices.json
      - ../resource-manager/Microsoft.Communication/preview/2024-09-01-preview/SenderUsernames.json
      - ../resource-manager/Microsoft.Communication/preview/2024-09-01-preview/SmtpUsernames.json
  - version: 2024-11-01-preview
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.Communication/preview/2024-11-01-preview/CommunicationServices.json
      - ../resource-manager/Microsoft.Communication/preview/2024-11-01-preview/Domains.json
      - ../resource-manager/Microsoft.Communication/preview/2024-11-01-preview/EmailServices.json
      - ../resource-manager/Microsoft.Communication/preview/2024-11-01-preview/SenderUsernames.json
      - ../resource-manager/Microsoft.Communication/preview/2024-11-01-preview/SmtpUsernames.json
  - version: 2025-01-25-preview
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.Communication/preview/2025-01-25-preview/CommunicationServices.json
      - ../resource-manager/Microsoft.Communication/preview/2025-01-25-preview/Domains.json
      - ../resource-manager/Microsoft.Communication/preview/2025-01-25-preview/EmailServices.json
      - ../resource-manager/Microsoft.Communication/preview/2025-01-25-preview/Locations.json
      - ../resource-manager/Microsoft.Communication/preview/2025-01-25-preview/SenderUsernames.json
      - ../resource-manager/Microsoft.Communication/preview/2025-01-25-preview/SmtpUsernames.json
  - version: 2025-05-01
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.Communication/stable/2025-05-01/CommunicationServices.json
      - ../resource-manager/Microsoft.Communication/stable/2025-05-01/Domains.json
      - ../resource-manager/Microsoft.Communication/stable/2025-05-01/EmailServices.json
      - ../resource-manager/Microsoft.Communication/stable/2025-05-01/SenderUsernames.json
  - version: 2025-05-01-preview
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.Communication/preview/2025-05-01-preview/CommunicationServices.json
      - ../resource-manager/Microsoft.Communication/preview/2025-05-01-preview/Domains.json
      - ../resource-manager/Microsoft.Communication/preview/2025-05-01-preview/EmailServices.json
      - ../resource-manager/Microsoft.Communication/preview/2025-05-01-preview/Locations.json
      - ../resource-manager/Microsoft.Communication/preview/2025-05-01-preview/SenderUsernames.json
      - ../resource-manager/Microsoft.Communication/preview/2025-05-01-preview/SmtpUsernames.json
  - version: 2025-09-01
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.Communication/stable/2025-09-01/openapi.json
  - version: 2025-09-01-preview
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.Communication/preview/2025-09-01-preview/CommunicationServices.json
      - ../resource-manager/Microsoft.Communication/preview/2025-09-01-preview/Domains.json
      - ../resource-manager/Microsoft.Communication/preview/2025-09-01-preview/EmailServices.json
      - ../resource-manager/Microsoft.Communication/preview/2025-09-01-preview/Locations.json
      - ../resource-manager/Microsoft.Communication/preview/2025-09-01-preview/SenderUsernames.json
      - ../resource-manager/Microsoft.Communication/preview/2025-09-01-preview/SmtpUsernames.json
  - version: 2026-03-18
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.Communication/stable/2026-03-18/openapi.json
