emit:
  - "@azure-tools/typespec-autorest"
parameters:
  "service-dir":
    default: "sdk/iotoperations"
options:
  "@azure-tools/typespec-autorest":
    emitter-output-dir: "{project-root}"
    azure-resource-provider-folder: "resource-manager"
    emit-common-types-schema: "never"
    output-file: "{version-status}/{version}/iotoperationsmq.json"
    arm-types-dir: "{project-root}/../../../../common-types/resource-management"
  "@azure-typespec/http-client-csharp-mgmt":
    namespace: "Azure.ResourceManager.IotOperations"
    emitter-output-dir: "{output-dir}/{service-dir}/{namespace}"
linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/resource-manager"
  disable:
    "@azure-tools/typespec-azure-resource-manager/arm-common-types-version": "New rule"
