versions:
  - version: 2023-12-01
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.BareMetal/preview/2023-12-01/BootstrapRP.json
  - version: 2025-02-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.BareMetal/preview/2025-02-01-preview/BootstrapRP.json
  - version: 2025-08-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.BareMetal/preview/2025-08-01-preview/BootstrapRP.json
  - version: 2026-04-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.BareMetal/preview/2026-04-01-preview/BootstrapRP.json
