versions:
  - version: 2025-05-15-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.PortalServices/copilotConnectors/preview/2025-05-15-preview/copilotConnectors.json
