versions:
  - version: 2025-10-01
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.Lionrock/stable/2025-10-01/lionrock.json
  - version: 2025-12-04-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.Lionrock/preview/2025-12-04-preview/lionrock.json
  - version: 2026-04-14-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.Lionrock/preview/2026-04-14-preview/lionrock.json
