versions:
  - version: 2026-04-16-preview
    source: typespec
    swagger-files:
      - preview/2026-04-16-preview/agentFabric.json
  - version: 2026-07-21-preview
    source: typespec
    swagger-files:
      - preview/2026-07-21-preview/agentFabric.json
