versions:
  - version: 2023-07-01-preview
    source: swagger
    swagger-files:
      - preview/2023-07-01-preview/operations.json
  - version: 2024-02-01-preview
    source: typespec
    swagger-files:
      - preview/2024-02-01-preview/operations.json
