versions:
  - version: 2025-02-01-preview
    source: typespec
    swagger-files:
      - ../../resource-manager/Microsoft.ApplicationMigration/preview/2025-02-01-preview/WorkloadsDiscovery.json
  - version: 2025-11-06-preview
    source: typespec
    swagger-files:
      - ../../resource-manager/Microsoft.ApplicationMigration/preview/2025-11-06-preview/WorkloadsDiscovery.json
