versions:
  - version: 2025-06-06-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.NetworkResourceProvider/preview/2025-06-06-preview/microsoft-networkresourceprovider.json
