versions:
  - version: 2025-03-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.ChangeSafety/SafeRollout/preview/2025-03-01-preview/SafeRollout.json
  - version: 2026-01-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.ChangeSafety/SafeRollout/preview/2026-01-01-preview/SafeRollout.json
