versions:
  - version: 2025-12-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.AwsConnector/preview/2025-12-01-preview/bedrockApplicationInferenceProfile.json
  - version: 2026-05-31-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.AwsConnector/preview/2026-05-31-preview/bedrockApplicationInferenceProfile.json
