versions:
  - version: 2025-05-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.HealthcareInterop/cloud/preview/2025-05-01-preview/cloud.json
  - version: 2025-06-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.HealthcareInterop/cloud/preview/2025-06-01-preview/cloud.json
  - version: 2025-10-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.HealthcareInterop/cloud/preview/2025-10-01-preview/cloud.json
  - version: 2025-11-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.HealthcareInterop/cloud/preview/2025-11-01-preview/cloud.json
