versions:
  - version: 2026-02-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.Validate/preview/2026-02-01-preview/validate.json
  - version: 2026-03-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.Validate/preview/2026-03-01-preview/validate.json
  - version: 2026-05-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.Validate/preview/2026-05-01-preview/validate.json
  - version: 2026-07-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.Validate/preview/2026-07-01-preview/validate.json
