parameters:
  service-dir:
    default: "sdk/impact"
emit:
  - "@azure-tools/typespec-autorest"
linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/resource-manager"
options:
  "@azure-tools/typespec-autorest":
    use-read-only-status-schema: true
    emitter-output-dir: "{project-root}/.."
    azure-resource-provider-folder: "resource-manager"
    output-file: "{azure-resource-provider-folder}/{service-name}/{version-status}/{version}/impact.json"
    version: "2026-05-01-preview"
  "@azure-typespec/http-client-csharp-mgmt":
    namespace: "Azure.ResourceManager.Impact"
    emitter-output-dir: "{output-dir}/{service-dir}/{namespace}"
  "@azure-tools/typespec-python":
    flavor: azure
    emitter-output-dir: "{output-dir}/{service-dir}/azure-mgmt-impact"
    namespace: "azure.mgmt.impact"
    generate-test: true
    generate-sample: true
  "@azure-tools/typespec-java":
    emitter-output-dir: "{output-dir}/{service-dir}/azure-resourcemanager-impact"
    flavor: azure
    namespace: "com.azure.resourcemanager.impact"
    service-name: "impact"
  "@azure-tools/typespec-ts":
    emitter-output-dir: "{output-dir}/{service-dir}/arm-impact"
    experimental-extensible-enums: true
    flavor: azure
    package-details:
      name: "@azure/arm-impact"
  "@azure-tools/typespec-go":
    service-dir: "sdk/resourcemanager/impact"
    emitter-output-dir: "{output-dir}/{service-dir}/armimpact"
    module: "github.com/Azure/azure-sdk-for-go/{service-dir}/armimpact"
    fix-const-stuttering: true
    generate-samples: true
    generate-fakes: true
    head-as-boolean: true
    inject-spans: true
