versions:
  - version: 2024-07-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.PortalServices/azurecoreexperiencesassistant/preview/2024-07-01-preview/azurecoreexperiencesassistant.json
  - version: 2024-08-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.PortalServices/azurecoreexperiencesassistant/preview/2024-08-01-preview/azurecoreexperiencesassistant.json
  - version: 2024-09-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.PortalServices/azurecoreexperiencesassistant/preview/2024-09-01-preview/azurecoreexperiencesassistant.json
