versions:
  - version: 2025-09-09-preview
    source: typespec
    swagger-files:
      - ../../resource-manager/Microsoft.ApplicationMigration/ConnectionHubs/preview/2025-09-09-preview/connectionhubs.json
