versions:
  - version: 2025-10-06-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.DatacenterHardware/preview/2025-10-06-preview/microsoft-datacenterhardware.json
  - version: 2025-12-02-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.DatacenterHardware/preview/2025-12-02-preview/microsoft-datacenterhardware.json
