versions:
  - version: 2023-08-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.AzureImageTestingForLinux/preview/2023-08-01-preview/azureimagetestingforlinux.json
  - version: 2025-04-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.AzureImageTestingForLinux/preview/2025-04-01-preview/azureimagetestingforlinux.json
