versions:
  - version: 2021-07-08-privatepreview
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.HybridConnectivity/preview/2021-07-08-privatepreview/hybridconnectivity.json
  - version: 2021-10-01-privatepreview
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.HybridConnectivity/preview/2021-10-01-privatepreview/hybridconnectivity.json
  - version: 2022-05-01-preview
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.HybridConnectivity/preview/2022-05-01-preview/hybridconnectivity.json
  - version: 2023-03-15
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.HybridConnectivity/stable/2023-03-15/hybridconnectivity.json
  - version: 2023-04-01-preview
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.HybridConnectivity/preview/2023-04-01-preview/hybridconnectivity.json
  - version: 2024-12-01
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.HybridConnectivity/stable/2024-12-01/hybridconnectivity.json
  - version: 2024-12-15-preview
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.HybridConnectivity/preview/2024-12-15-preview/hybridconnectivity.json
  - version: 2025-12-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.HybridConnectivity/preview/2025-12-01-preview/hybridconnectivity.json
  - version: 2026-04-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.HybridConnectivity/preview/2026-04-01-preview/hybridconnectivity.json
  - version: 2026-09-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.HybridConnectivity/preview/2026-09-01-preview/hybridconnectivity.json
