versions:
  - version: 2020-01-01-preview
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.Contoso/preview/2020-01-01-preview/extensionclusters.json
      - ../resource-manager/Microsoft.Contoso/preview/2020-01-01-preview/recipe.json
      - ../resource-manager/Microsoft.Contoso/preview/2020-01-01-preview/tower.json
  - version: 2021-04-01-preview
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.Contoso/preview/2021-04-01-preview/cnab.json
  - version: 2021-10-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.Contoso/preview/2021-10-01-preview/openapi.json
  - version: 2022-10-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.Contoso/preview/2022-10-01-preview/openapi.json
  - version: 2023-10-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.Contoso/preview/2023-10-01-preview/openapi.json
  - version: 2023-11-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.Contoso/preview/2023-11-01-preview/openapi.json
  - version: 2023-12-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.Contoso/preview/2023-12-01-preview/openapi.json
