versions:
  - version: 2025-02-01-preview
    source: typespec
    swagger-files:
      - ../../resource-manager/Microsoft.ApplicationMigration/Mongo/preview/2025-02-01-preview/MongoWorkloadsDiscovery.json
  - version: 2026-05-01-preview
    source: typespec
    swagger-files:
      - ../../resource-manager/Microsoft.ApplicationMigration/Mongo/preview/2026-05-01-preview/MongoWorkloadsDiscovery.json
