versions:
  - version: 2023-06-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.HealthDataAIServices/preview/2023-06-01-preview/openapi.json
  - version: 2024-02-28-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.HealthDataAIServices/preview/2024-02-28-preview/openapi.json
