versions:
  - version: 2022-06-09-preview
    source: swagger
    swagger-files:
      - preview/2022-06-09-preview/dellstorage.json
  - version: 2025-03-21
    source: typespec
    swagger-files:
      - stable/2025-03-21/Dell.Storage.json
  - version: 2025-03-21-preview
    source: typespec
    swagger-files:
      - preview/2025-03-21-preview/Dell.Storage.json
  - version: 2026-03-01-preview
    source: typespec
    swagger-files:
      - preview/2026-03-01-preview/Dell.Storage.json
