versions:
  - version: 2022-12-31-preview
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.CleanRoom/preview/2022-12-31-preview/cleanrooms.json
      - ../resource-manager/Microsoft.CleanRoom/preview/2022-12-31-preview/commonTypes.json
      - ../resource-manager/Microsoft.CleanRoom/preview/2022-12-31-preview/microservices.json
      - ../resource-manager/Microsoft.CleanRoom/preview/2022-12-31-preview/operations.json
  - version: 2025-10-31-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.CleanRoom/preview/2025-10-31-preview/openapi.json
  - version: 2026-03-31-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.CleanRoom/preview/2026-03-31-preview/openapi.json
  - version: 2026-04-30-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.CleanRoom/preview/2026-04-30-preview/openapi.json
