versions:
  - version: 2024-11-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.UpdateManager/preview/2024-11-01-preview/updatemanager.json
  - version: 2024-12-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.UpdateManager/preview/2024-12-01-preview/updatemanager.json
  - version: 2025-06-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.UpdateManager/preview/2025-06-01-preview/updatemanager.json
  - version: 2025-08-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.UpdateManager/preview/2025-08-01-preview/updatemanager.json
