versions:
  - version: 2019-12-04-preview
    source: swagger
    swagger-files:
      - preview/2019-12-04-preview/ConnectedCache.json
  - version: 2021-09-15-preview
    source: swagger
    swagger-files:
      - preview/2021-09-15-preview/ConnectedCache.json
  - version: 2022-03-21-preview
    source: swagger
    swagger-files:
      - preview/2022-03-21-preview/ConnectedCache.json
  - version: 2023-04-01-preview
    source: swagger
    swagger-files:
      - preview/2023-04-01-preview/ConnectedCache.json
  - version: 2023-05-01-preview
    source: typespec
    swagger-files:
      - preview/2023-05-01-preview/ConnectedCache.json
  - version: 2024-11-30-preview
    source: typespec
    swagger-files:
      - preview/2024-11-30-preview/ConnectedCache.json
  - version: 2025-06-15
    source: typespec
    swagger-files:
      - stable/2025-06-15/ConnectedCache.json
  - version: 2026-06-01
    source: typespec
    swagger-files:
      - stable/2026-06-01/ConnectedCache.json
