versions:
  - version: 2026-06-30-preview
    source: typespec
    swagger-files:
      - preview/2026-06-30-preview/microsoft-securitycontext.json
  - version: 2026-07-13-preview
    source: typespec
    swagger-files:
      - preview/2026-07-13-preview/microsoft-securitycontext.json
