versions:
  - version: 2025-05-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.HealthcareInterop/edge/preview/2025-05-01-preview/edge.json
  - version: 2025-06-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.HealthcareInterop/edge/preview/2025-06-01-preview/edge.json
