versions:
  - version: 2024-06-01-preview
    source: typespec
    swagger-files:
      - preview/2024-06-01-preview/computeschedule.json
  - version: 2024-08-01-preview
    source: typespec
    swagger-files:
      - preview/2024-08-01-preview/computeschedule.json
  - version: 2025-04-15-preview
    source: typespec
    swagger-files:
      - preview/2025-04-15-preview/computeschedule.json
  - version: 2026-03-01-preview
    source: typespec
    swagger-files:
      - preview/2026-03-01-preview/computeschedule.json
  - version: 2026-04-27-preview
    source: typespec
    swagger-files:
      - preview/2026-04-27-preview/computeschedule.json
