versions:
  - version: 2026-06-01-preview
    source: typespec
    swagger-files:
      - ../../resource-manager/Microsoft.ApplicationMigration/Container/preview/2026-06-01-preview/ContainerWorkloadsDiscovery.json
