versions:
  - version: 2026-06-01-preview
    source: typespec
    swagger-files:
      - preview/2026-06-01-preview/migrateProjects.json
  - version: 2026-06-15-preview
    source: typespec
    swagger-files:
      - preview/2026-06-15-preview/migrateProjects.json
