versions:
  - version: 2025-09-09-preview
    source: typespec
    swagger-files:
      - ../../resource-manager/Microsoft.ApplicationMigration/CodeScanSites/preview/2025-09-09-preview/codescansites.json
  - version: 2026-05-12-preview
    source: typespec
    swagger-files:
      - ../../resource-manager/Microsoft.ApplicationMigration/CodeScanSites/preview/2026-05-12-preview/codescansites.json
