versions:
  - version: 2023-09-28-preview
    source: typespec
    swagger-files:
      - preview/2023-09-28-preview/sovereign.json
  - version: 2024-03-31-preview
    source: typespec
    swagger-files:
      - preview/2024-03-31-preview/sovereign.json
  - version: 2024-10-31-preview
    source: typespec
    swagger-files:
      - preview/2024-10-31-preview/sovereign.json
  - version: 2026-03-15-preview
    source: typespec
    swagger-files:
      - preview/2026-03-15-preview/sovereign.json
  - version: 2026-07-31-preview
    source: typespec
    swagger-files:
      - preview/2026-07-31-preview/sovereign.json
