versions:
  - version: 2020-12-14-preview
    source: swagger
    swagger-files:
      - preview/2020-12-14-preview/codeSigningAccount.json
  - version: 2023-04-30-preview
    source: swagger
    swagger-files:
      - preview/2023-04-30-preview/codeSigningAccount.json
  - version: 2024-02-05-preview
    source: typespec
    swagger-files:
      - preview/2024-02-05-preview/codeSigningAccount.json
  - version: 2024-09-30-preview
    source: typespec
    swagger-files:
      - preview/2024-09-30-preview/codeSigningAccount.json
  - version: 2025-10-13
    source: typespec
    swagger-files:
      - stable/2025-10-13/codeSigningAccount.json
  - version: 2025-11-20-preview
    source: typespec
    swagger-files:
      - preview/2025-11-20-preview/codeSigningAccount.json
