versions:
  - version: 2024-10-03-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.LiftrPilot/preview/2024-10-03-preview/pilot.json
  - version: 2025-04-03-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.LiftrPilot/preview/2025-04-03-preview/pilot.json
  - version: 2025-04-18-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.LiftrPilot/preview/2025-04-18-preview/pilot.json
  - version: 2025-05-21-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.LiftrPilot/preview/2025-05-21-preview/pilot.json
  - version: 2025-05-23-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.LiftrPilot/preview/2025-05-23-preview/pilot.json
  - version: 2025-10-24-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.LiftrPilot/preview/2025-10-24-preview/pilot.json
  - version: 2026-01-29-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.LiftrPilot/preview/2026-01-29-preview/pilot.json
  - version: 2026-04-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.LiftrPilot/preview/2026-04-01-preview/pilot.json
  - version: 2026-06-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.LiftrPilot/preview/2026-06-01-preview/pilot.json
