versions:
  - version: 2023-08-22
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.AzureCis/stable/2023-08-22/plannedQuota.json
  - version: 2023-08-22-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.AzureCis/preview/2023-08-22-preview/plannedQuota.json
  - version: 2024-06-24-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.AzureCis/preview/2024-06-24-preview/plannedQuota.json
  - version: 2025-12-04-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.AzureCis/preview/2025-12-04-preview/plannedQuota.json
