versions:
  - version: 2023-09-01-preview
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.EdgeManagement/preview/2023-09-01-preview/chat.json
  - version: 2025-03-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.EdgeManagement/preview/2025-03-01-preview/chat.json
  - version: 2025-06-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.EdgeManagement/preview/2025-06-01-preview/chat.json
