// -----------------------------------------------------------------------
// <copyright file="main.tsp" company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation. All rights reserved.
// </copyright>
// -----------------------------------------------------------------------

// Import the shared main file for all common Azure Encrypted Transport service types
import "./sharedResources.tsp";

// Microsoft.EncryptedTransport service
import "./encryptedTransportService.tsp";
