// -----------------------------------------------------------------------
// <copyright file="sharedResources.tsp" company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation. All rights reserved.
// </copyright>
// -----------------------------------------------------------------------

import "./base.tsp";
import "./resources/encryptedTransportAccount.tsp";
import "./resources/device.tsp";
import "./resources/deviceProfile.tsp";
