versions:
  - version: 2025-04-02-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.NetworkServiceManager/preview/2025-04-02-preview/networkservicemanager.json
  - version: 2025-05-21-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.NetworkServiceManager/preview/2025-05-21-preview/networkservicemanager.json
