versions:
  - version: 2024-10-01-preview
    source: typespec
    swagger-files:
      - preview/2024-10-01-preview/resourceInsights.json
  - version: 2026-04-01-preview
    source: typespec
    swagger-files:
      - preview/2026-04-01-preview/resourceInsights.json
