versions:
  - version: 2026-04-24-preview
    source: typespec
    swagger-files:
      - preview/2026-04-24-preview/offers.json
  - version: 2026-06-30-preview
    source: typespec
    swagger-files:
      - preview/2026-06-30-preview/offers.json
