versions:
  - version: 2021-06-01-preview
    source: swagger
    swagger-files:
      - preview/2021-06-01-preview/oep.json
  - version: 2022-04-04-preview
    source: swagger
    swagger-files:
      - preview/2022-04-04-preview/oep.json
  - version: 2022-07-21-preview
    source: swagger
    swagger-files:
      - preview/2022-07-21-preview/oep.json
  - version: 2022-12-01-preview
    source: swagger
    swagger-files:
      - preview/2022-12-01-preview/meds.json
  - version: 2023-02-21-preview
    source: swagger
    swagger-files:
      - preview/2023-02-21-preview/oep.json
  - version: 2023-06-12
    source: swagger
    swagger-files:
      - stable/2023-06-12/oep.json
  - version: 2023-10-01-preview
    source: swagger
    swagger-files:
      - preview/2023-10-01-preview/oep.json
  - version: 2023-11-12
    source: swagger
    swagger-files:
      - stable/2023-11-12/oep.json
  - version: 2024-02-09-preview
    source: swagger
    swagger-files:
      - preview/2024-02-09-preview/oep.json
  - version: 2024-05-21
    source: swagger
    swagger-files:
      - stable/2024-05-21/oep.json
  - version: 2025-08-06
    source: swagger
    swagger-files:
      - stable/2025-08-06/oep.json
  - version: 2025-09-22-preview
    source: swagger
    swagger-files:
      - preview/2025-09-22-preview/oep.json
  - version: 2025-11-11
    source: swagger
    swagger-files:
      - stable/2025-11-11/oep.json
  - version: 2025-12-15
    source: swagger
    swagger-files:
      - stable/2025-12-15/oep.json
  - version: 2026-02-02-preview
    source: typespec
    swagger-files:
      - preview/2026-02-02-preview/oep.json
  - version: 2026-07-21-preview
    source: typespec
    swagger-files:
      - preview/2026-07-21-preview/oep.json
