parameters:
  "service-dir":
    default: "sdk/oep"
emit:
  - "@azure-tools/typespec-autorest"
options:
  "@azure-tools/typespec-autorest":
    omit-unreachable-types: true
    use-read-only-status-schema: true
    emitter-output-dir: "{project-root}"
    arm-types-dir: "{project-root}/../../../../common-types/resource-management"
    azure-resource-provider-folder: "resource-manager"
    output-file: "{version-status}/{version}/oep.json"
    emit-lro-options: "all"
    examples-dir: "{project-root}/examples"
  "@azure-tools/typespec-python":
    emitter-output-dir: "{output-dir}/{service-dir}/azure-mgmt-oep"
    namespace: "azure.mgmt.oep"
    generate-test: true
    generate-sample: true
    flavor: "azure"
  "@azure-tools/typespec-java":
    emitter-output-dir: "{output-dir}/{service-dir}/azure-resourcemanager-oep"
    namespace: "com.azure.resourcemanager.oep"
    service-name: "OpenEnergyPlatform"
    flavor: "azure"
  "@azure-tools/typespec-ts":
    emitter-output-dir: "{output-dir}/{service-dir}/arm-oep"
    flavor: "azure"
    experimental-extensible-enums: true
    package-details:
      name: "@azure/arm-oep"
  "@azure-tools/typespec-go":
    service-dir: "sdk/resourcemanager/oep"
    emitter-output-dir: "{output-dir}/{service-dir}/armoep"
    module: "github.com/Azure/azure-sdk-for-go/{service-dir}/armoep"
    fix-const-stuttering: false
    flavor: "azure"
    generate-samples: true
    generate-fakes: true
    head-as-boolean: true
    inject-spans: true
linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/resource-manager"
