versions:
  - version: 2025-02-01-preview
    source: typespec
    swagger-files:
      - ../../resource-manager/Microsoft.ApplicationMigration/ApplicationDiscovery/preview/2025-02-01-preview/appfingerprinting.json
  - version: 2026-01-01-preview
    source: typespec
    swagger-files:
      - ../../resource-manager/Microsoft.ApplicationMigration/ApplicationDiscovery/preview/2026-01-01-preview/appfingerprinting.json
  - version: 2026-02-02-preview
    source: typespec
    swagger-files:
      - ../../resource-manager/Microsoft.ApplicationMigration/ApplicationDiscovery/preview/2026-02-02-preview/appfingerprinting.json
