versions:
  - version: 2025-05-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.StorageInventory/preview/2025-05-01-preview/microsoft-storageinventory.json
  - version: 2026-07-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.StorageInventory/preview/2026-07-01-preview/microsoft-storageinventory.json
