versions:
  - version: 2020-01-20-preview
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.Falcon/preview/2020-01-20-preview/falcon.json
  - version: 2020-09-02-preview
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.Falcon/preview/2020-09-02-preview/falcon.json
  - version: 2024-10-14-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.Falcon/preview/2024-10-14-preview/falcon.json
  - version: 2025-03-26-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.Falcon/preview/2025-03-26-preview/falcon.json
  - version: 2025-05-14-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.Falcon/preview/2025-05-14-preview/falcon.json
  - version: 2026-03-30-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.Falcon/preview/2026-03-30-preview/falcon.json
