parameters:
  "service-dir":
    default: "sdk/aiops"
emit:
  - "@azure-tools/typespec-autorest"
options:
  "@azure-tools/typespec-autorest":
    use-read-only-status-schema: true
    azure-resource-provider-folder: "resource-manager"
    emitter-output-dir: "{project-root}/.."
    output-file: "{azure-resource-provider-folder}/{service-name}/{version-status}/{version}/aiops.json"
    emit-common-types-schema: "never"
    omit-unreachable-types: true
  "@azure-tools/typespec-csharp":
    flavor: azure
    emitter-output-dir: "{output-dir}/{service-dir}/Azure.ResourceManager.AIOps"
    clear-output-folder: true
    model-namespace: true
    namespace: "Azure.ResourceManager.AIOps"
  "@azure-tools/typespec-python":
    emitter-output-dir: "{output-dir}/{service-dir}/azure-mgmt-aiops"
    package-name: "azure-mgmt-aiops"
    generate-test: true
    generate-sample: true
    flavor: "azure"
    namespace: azure.mgmt.aiops
  "@azure-tools/typespec-java":
    emitter-output-dir: "{output-dir}/{service-dir}/azure-resourcemanager-aiops"
    namespace: "com.azure.resourcemanager.aiops"
    service-name: "aiops"
    flavor: azure
  "@azure-tools/typespec-ts":
    emitter-output-dir: "{output-dir}/{service-dir}/arm-aiops"
    experimental-extensible-enums: true
    is-modular-library: true
    flavor: "azure"
    package-details:
      name: "@azure/arm-aiops"
  "@azure-tools/typespec-go":
    service-dir: "sdk/resourcemanager/aiops"
    emitter-output-dir: "{output-dir}/{service-dir}/armaiops"
    module: "github.com/Azure/azure-sdk-for-go/{service-dir}/armaiops"
    fix-const-stuttering: true
    flavor: "azure"
    generate-examples: true
    generate-fakes: true
    head-as-boolean: true
    inject-spans: true
    generate-samples: true
linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/resource-manager"
