versions:
  - version: 2026-01-01-preview
    source: typespec
    swagger-files:
      - ../../resource-manager/Microsoft.ApplicationMigration/Network/preview/2026-01-01-preview/NetworkDiscovery.json
  - version: 2026-08-01-preview
    source: typespec
    swagger-files:
      - ../../resource-manager/Microsoft.ApplicationMigration/Network/preview/2026-08-01-preview/NetworkDiscovery.json
