versions:
  - version: 2025-10-06-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.DatacenterProductionInventory/preview/2025-10-06-preview/microsoft-datacenterproductioninventory.json
