versions:
  - version: 2022-05-10-beta
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.AppComplianceAutomation/preview/2022-05-10-beta/appcomplianceautomation.json
  - version: 2022-05-10-privatepreview
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.AppComplianceAutomation/preview/2022-05-10-privatepreview/appcomplianceautomation.json
  - version: 2022-11-16-preview
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.AppComplianceAutomation/preview/2022-11-16-preview/appcomplianceautomation.json
  - version: 2023-02-15-preview
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.AppComplianceAutomation/preview/2023-02-15-preview/appcomplianceautomation.json
  - version: 2024-06-27
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.AppComplianceAutomation/stable/2024-06-27/appcomplianceautomation.json
  - version: 2024-12-15-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.AppComplianceAutomation/preview/2024-12-15-preview/appcomplianceautomation.json
