versions:
  - version: 2024-06-24-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.Titan/preview/2024-06-24-preview/titan.json
  - version: 2025-03-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.Titan/preview/2025-03-01-preview/titan.json
  - version: 2025-06-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.Titan/preview/2025-06-01-preview/titan.json
  - version: 2026-04-22-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.Titan/preview/2026-04-22-preview/titan.json
  - version: 2026-05-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.Titan/preview/2026-05-01-preview/titan.json
  - version: 2026-07-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.Titan/preview/2026-07-01-preview/titan.json
