versions:
  - version: 2023-07-12-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.Hardware/preview/2023-07-12-preview/hardware.json
  - version: 2025-12-04-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.Hardware/preview/2025-12-04-preview/hardware.json
  - version: 2026-02-26-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.Hardware/preview/2026-02-26-preview/hardware.json
