versions:
  - version: 2024-09-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.PortalServices/settings/preview/2024-09-01-preview/settings.json
  - version: 2025-04-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.PortalServices/settings/preview/2025-04-01-preview/settings.json
  - version: 2025-09-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.PortalServices/settings/preview/2025-09-01-preview/settings.json
  - version: 2025-11-01
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.PortalServices/settings/stable/2025-11-01/settings.json
  - version: 2026-02-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.PortalServices/settings/preview/2026-02-01-preview/settings.json
  - version: 2026-07-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.PortalServices/settings/preview/2026-07-01-preview/settings.json
