versions:
  - version: 2020-02-01-preview
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.FootprintMonitoring/preview/2020-02-01-preview/footprintProfiles.json
  - version: 2024-09-16-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.FootprintMonitoring/preview/2024-09-16-preview/footprintProfiles.json
