versions:
  - version: 2024-04-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.PortalServices/copilotSettings/preview/2024-04-01-preview/copilotSettings.json
  - version: 2024-07-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.PortalServices/copilotSettings/preview/2024-07-01-preview/copilotSettings.json
  - version: 2024-08-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.PortalServices/copilotSettings/preview/2024-08-01-preview/copilotSettings.json
  - version: 2024-09-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.PortalServices/copilotSettings/preview/2024-09-01-preview/copilotSettings.json
  - version: 2025-08-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.PortalServices/copilotSettings/preview/2025-08-01-preview/copilotSettings.json
  - version: 2025-09-10-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.PortalServices/copilotSettings/preview/2025-09-10-preview/copilotSettings.json
  - version: 2026-07-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.PortalServices/copilotSettings/preview/2026-07-01-preview/copilotSettings.json
