versions:
  - version: 2024-01-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.Inventory/preview/2024-01-01-preview/microsoftinventory.json
  - version: 2024-11-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.Inventory/preview/2024-11-01-preview/microsoftinventory.json
  - version: 2025-03-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.Inventory/preview/2025-03-01-preview/microsoftinventory.json
