versions:
  - version: 2018-11-01-preview
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.Contoso/preview/2018-11-01-preview/employee.json
  - version: 2019-01-01
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.Contoso/stable/2019-01-01/employee.json
  - version: 2020-01-01-preview
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.Contoso/preview/2020-01-01-preview/cluster.json
      - ../resource-manager/Microsoft.Contoso/preview/2020-01-01-preview/employee.json
  - version: 2024-06-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.Contoso/preview/2024-06-01-preview/openapi.json
