versions:
  - version: 2024-01-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.Frontdoor/preview/2024-01-01-preview/microsoftfrontdoor.json
  - version: 2025-08-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.Frontdoor/preview/2025-08-01-preview/microsoftfrontdoor.json
