versions:
  - version: 2021-06-01-preview
    source: swagger
    swagger-files:
      - preview/2021-06-01-preview/dynatrace.json
  - version: 2021-09-01
    source: swagger
    swagger-files:
      - stable/2021-09-01/dynatrace.json
  - version: 2021-09-01-preview
    source: swagger
    swagger-files:
      - preview/2021-09-01-preview/dynatrace.json
  - version: 2022-10-01-preview
    source: swagger
    swagger-files:
      - preview/2022-10-01-preview/dynatrace.json
  - version: 2023-03-01-preview
    source: swagger
    swagger-files:
      - preview/2023-03-01-preview/dynatrace.json
  - version: 2023-04-20-preview
    source: swagger
    swagger-files:
      - preview/2023-04-20-preview/dynatrace.json
  - version: 2023-04-27
    source: swagger
    swagger-files:
      - stable/2023-04-27/dynatrace.json
  - version: 2023-08-14-preview
    source: swagger
    swagger-files:
      - preview/2023-08-14-preview/dynatrace.json
  - version: 2023-08-22-preview
    source: swagger
    swagger-files:
      - preview/2023-08-22-preview/dynatrace.json
  - version: 2023-09-12-preview
    source: swagger
    swagger-files:
      - preview/2023-09-12-preview/dynatrace.json
  - version: 2023-09-20-preview
    source: swagger
    swagger-files:
      - preview/2023-09-20-preview/dynatrace.json
  - version: 2023-11-11-preview
    source: swagger
    swagger-files:
      - preview/2023-11-11-preview/dynatrace.json
  - version: 2023-11-24-preview
    source: swagger
    swagger-files:
      - preview/2023-11-24-preview/dynatrace.json
  - version: 2024-04-24
    source: typespec
    swagger-files:
      - stable/2024-04-24/dynatrace.json
  - version: 2024-04-24-preview
    source: swagger
    swagger-files:
      - preview/2024-04-24-preview/dynatrace.json
  - version: 2025-11-03-preview
    source: typespec
    swagger-files:
      - preview/2025-11-03-preview/dynatrace.json
  - version: 2026-01-07-preview
    source: typespec
    swagger-files:
      - preview/2026-01-07-preview/dynatrace.json
