versions:
  - version: 2024-10-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.ChangeSafety/validation/preview/2024-10-01-preview/validation.json
  - version: 2025-01-15-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.ChangeSafety/validation/preview/2025-01-15-preview/validation.json
  - version: 2026-01-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.ChangeSafety/validation/preview/2026-01-01-preview/validation.json
