versions:
  - version: 2025-01-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.Storage/storageDataManagement/preview/2025-01-01-preview/StorageDataManagementRP.json
  - version: 2025-05-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.Storage/storageDataManagement/preview/2025-05-01-preview/StorageDataManagementRP.json
  - version: 2025-07-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.Storage/storageDataManagement/preview/2025-07-01-preview/StorageDataManagementRP.json
